trigger:
  branches:
    include:
      - test  # or the branch you want to trigger the build

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'my-app'
  acrName: 'nnpacr01'  # Your ACR name
  acrLoginServer: 'nnpacr01.azurecr.io'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'your-service-connection'  # Replace with your Azure service connection
    repository: '$(acrName)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    #tags: 'latest'
    tags: |
      $(imageName):$(Build.BuildId)

- task: AzureCLI@2
  displayName: 'Deploy to Azure'
  inputs:
    azureSubscription: 'your-service-connection'  # Replace with your Azure service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr run --name $(acrName) --cmd "docker run $(acrLoginServer)/$(imageName):latest" /dev/null
